version: '3.8'
services:
  backend-e2e:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8081:9428"
    volumes:
      - my_volume:/app/data
    entrypoint: [ "npm", "run", "start:e2e"]
    networks:
      - ps6-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  frontend-e2e:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
      - ENVIRONMENT=production-e2e
    ports:
      - "8080:80"
    networks:
      - ps6-network
    depends_on:
      - backend-e2e
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  test-e2e:
    build:
      context: ../front-end
      dockerfile: Dockerfile.e2e
    volumes:
      - test_results:/app/test-results
    ports:
      - "9323:9323"
    networks:
      - ps6-network
    environment:
      - TEST_URL=http://frontend-e2e
    depends_on:
      - frontend-e2e
      - backend-e2e
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9323"]
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  my_volume:
  test_results:

networks:
  ps6-network:
    driver: bridge
    
